name: "Backend Deployment"

on:

	push:

  		branches: [main]

jobs:

	deployment:

  	runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Backend

    run: echo "Running Backend!!"
